name: GEmini API Call

on:
  schedule:
    # - cron: '0 10 * * *' # Runs at 10 AM UTC
    - cron: '*/1 * * * *' # Runs every minute

jobs:
  call-GEMINI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run GEMINI script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DATABASE_USER_NAME: ${{ secrets.DATABASE_USER_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_CLUSTER: ${{ secrets.DATABASE_CLUSTER }}
          DATABASE_APP_NAME: ${{ secrets.DATABASE_APP_NAME }}
        run: node dist/index.js